[project]
name = "cb-etl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "lxml>=5.4.0",
    "pandas>=2.3.0",
    "requests>=2.32.3",
]
